.\" See LICENSE file for copyright and license details.
.Dd August 08, 2023
.Dt XKBSWITCH 1
.Os xkbswitch @VERSION@
.Sh NAME
.Nm xkbswitch
.Nd keyboard layout switcher for X
.Sh SYNOPSIS
.Nm
.Oo
.Cm 0 | 1 | 2 | 3
.Oc
.Sh DESCRIPTION
.Nm
sets (or gets) the current keyboard layout group index in the range of
0..3 (since 4 group limit is forced by XKB protocol format).
.Pp
If no arguments are given, then
.Nm
prints the current layout group index.
.Sh SEE ALSO
.Xr setxkbmap 1
